### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by grantstephens** [bigjosh/TSL#65]
Hello :wave: 

Could you please add a license to this repo. It is an incredible device and would like to make something similar.

Thanks in advance.

**Comment by grantstephens** [comment]
Perfect- thank you! It really is a pity these can't be purchased somewhere.

**Comment by bigjosh** [comment]
They can be purchased at lots of places! For example, here!....


https://www.uncommongoods.com/product/time-since-launch-clock
